version: '3.8'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=CleanArchitectureDb_Dev;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
      - JWT__Key=ThisIsASecretKeyForJWTTokenGenerationAndShouldBeAtLeast256BitsLong_DEV
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/logs:/app/logs
    ports:
      - "5001:80"  # Different port for dev

  angular:
    build:
      context: ./frontend/admin
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./frontend/admin/src:/app/src
      - /app/node_modules
    environment:
      - API_URL=http://localhost:5001
      - NODE_ENV=development

  # Additional services for development
  pgadmin:
    image: dpage/pgadmin4
    container_name: cleanarch-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    networks:
      - cleanarch-network

  # MongoDB Express for database management
  mongo-express:
    image: mongo-express
    container_name: cleanarch-mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin123@mongodb:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - cleanarch-network